# Generated by Django 5.2.17 on 2026-08-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alert_on_volume_milestone',
            field=models.BooleanField(default=True),
        ),
    ]
