# Generated by Django 5.2.17 on 2026-08-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_messagingserviceconfig_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='environment',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
